cookie_consent:
  consent_configuration:
    consent_cookie:
      expires: 'P180D'
      domain: null
      secure: true
      http_only: true
      same_site: 'lax'
    consent_categories:
      functional:
        - bookmark
        - shopping_cart
      social_media:
        - twitter
        - facebook
        - instagram
        - linkedin
        - pinterest
        - youtube
      analytics:
        - google_analytics
      tracking:
        - facebook_pixel
      marketing:
        - google_adsense
  persist_consent: true
  position: 'dialog'
  form_action: 'cookie_consent.update'
  csrf_protection: true
